### ISSUE TITLE
Random game app start CTD due vanilla BP-parented STE classes

### ISSUE THREAD

**Issue by DarthPointer** [DarthPointer/CVO#13]

**Comment by DarthPointer** [comment]
Fixed

**Comment by GreyHound6** [comment]
This keeps happening with other STEs derived from the base ScoutSpeedBoost class - this time it's the GK2 T5A one that causes me issues.

**Comment by GreyHound6** [comment]
Here's the crash message: 
`Fatal error: [File:Unknown] [Line: 135] StatChangeStatusEffectItem /Game/WeaponsNTools/GrapplingGun/STE_ScoutSpeedBoost.Default__STE_ScoutSpeedBoost_C:StatChangeStatusEffectItem_0 had RF_NeedLoad when being set up as an archetype of Class /Script/FSD.StatChangeStatusEffectItem in STE_AssaultRifle_E_SpeedBoost_C /Game/CVO/AssaultRifle/Upgrades/E/STE_AssaultRifle_E_SpeedBoost.Default__STE_AssaultRifle_E_SpeedBoost_C`
