### ISSUE TITLE
Weapon mods that affect RechargeTime/UnjamTime cannot have their values changed through UE or Hex-editing

### ISSUE THREAD

**Issue by GreyHound6** [DarthPointer/CVO#25]
Something's wrong with GSG code apparently. Shield Generator's T1A and T2A suffer from the same issue. Affects #16 #24 and might be an issue for many other mechanics of the same type.

**Comment by DarthPointer** [comment]
![изображение](https://user-images.githubusercontent.com/48957477/173248175-3a1f667b-275b-45bf-9dc6-61b1095f72a8.png)

I have been able to change the effect amount by replacing the file in-situ with a minimal asset from UE. Something must be wrong on your side.
